version: '3'
networks:
  kong-net:
    driver: bridge
services:
  # ---------------------
  # 安装 PostgreSQL 数据库
  # ---------------------
  kong-database:
    image: postgres:9.6
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_USER: konguser
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpwd
    volumes:
      - /apps/kong/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-V"]
      interval: 5s
      timeout: 5s
      retries: 5
  # ---------------------
  # 执行数据库迁移
  # ---------------------
  kong-migration:
    image: kong/kong-gateway:3.4.1.1
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_USER=konguser
      - KONG_PG_PASSWORD=kongpwd
      - KONG_PG_HOST=kong-database
    links:
      - kong-database
    depends_on:
      - kong-database
  # ---------------------
  # Kong gateway https://docs.konghq.com/gateway/latest/install/docker/
  # ---------------------
  kong:
    image: kong/kong-gateway:3.4.1.1
    restart: always
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: konguser
      KONG_PG_PASSWORD: kongpwd
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    depends_on:
      - kong-migration
    links:
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8443:8443"
      - "8444:8444"
      - "8445:8445"
  # ---------------------
  # Konga 预装数据库
  # ---------------------
  konga-prepare:
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://konguser:kongpwd@kong-database:5432/konga"
    networks:
      - kong-net
    restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database
  # ---------------------
  # Konga
  # ---------------------
  konga:
    image: pantsel/konga:latest
    restart: always
    networks:
      - kong-net
    environment:
      NODE_ENV: production
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_USER: konguser
      DB_DATABASE: konga
      DB_PASSWORD: kongpwd
    depends_on:
      - kong
      - kong-database
      - konga-prepare
    ports:
      - "1337:1337"