.PHONY: up stop down restart

up:
	docker-compose -f docker-compose.yml up -d

stop:
	docker-compose -f docker-compose.yml stop

down:
	docker-compose -f docker-compose.yml down

restart:
	docker-compose -f docker-compose.yml restart